### PR TITLE
[iDSK] Fixed data corruption on force-adding file

### PR DESCRIPTION
**Pull request by lronaldo**
* Using -f (force) to add a file that didn't exist in DSK caused corruption

### CODE REVIEW

**Comment by pulkomandy** [comment]
Looks good, but your changes don't follow the indentation used in the file. Can you check this? (or reindent the whole function if you think that's better).

**Comment by lronaldo** [comment]
Ops, sorry. I normally use spaces for indentation. I may rewrite it using tabs, do you prefer it that way?

**Comment by pulkomandy** [comment]
I don)t have a strong preference, as long as things are kept consistant in the file.

**Comment by lronaldo** [comment]
I've rewritten it using 8-space-sized tabs, as the rest of the code seems to be. Hope it is fine this time :)

**Comment by pulkomandy** [comment]
Thanks!

**Comment by lronaldo** [comment]
It's a pleasure :)

**Pull request merged**
